//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed, retrying in 2s....
        /// </summary>
        internal static string AuthenticationFailedRetryingIn2s {
            get {
                return ResourceManager.GetString("AuthenticationFailedRetryingIn2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Message from {0}: {1}.
        /// </summary>
        internal static string ChatMessageFrom {
            get {
                return ResourceManager.GetString("ChatMessageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the trade session..
        /// </summary>
        internal static string CouldNotStartTheTradeSession {
            get {
                return ResourceManager.GetString("CouldNotStartTheTradeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from Steam Network!.
        /// </summary>
        internal static string DisconnectedFromSteamNetwork {
            get {
                return ResourceManager.GetString("DisconnectedFromSteamNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Loading Bot..
        /// </summary>
        internal static string DoneLoadingBot {
            get {
                return ResourceManager.GetString("DoneLoadingBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged off Steam.  Reason: .
        /// </summary>
        internal static string LoggedOffSteamReason {
            get {
                return ResourceManager.GetString("LoggedOffSteamReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged On Callback: .
        /// </summary>
        internal static string LoggedOnCallback {
            get {
                return ResourceManager.GetString("LoggedOnCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error: .
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received new WebAPIUserNonce..
        /// </summary>
        internal static string ReceivedNewWebAPIUserNonce {
            get {
                return ResourceManager.GetString("ReceivedNewWebAPIUserNonce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerated 2FA code..
        /// </summary>
        internal static string Regenerated2FACode {
            get {
                return ResourceManager.GetString("Regenerated2FACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Bot Logged In Completely!.
        /// </summary>
        internal static string SteamBotLoggedInCompletely {
            get {
                return ResourceManager.GetString("SteamBotLoggedInCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Accepted!.
        /// </summary>
        internal static string TradeAccepted {
            get {
                return ResourceManager.GetString("TradeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade failed:.
        /// </summary>
        internal static string TradeFailed {
            get {
                return ResourceManager.GetString("TradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Opened..
        /// </summary>
        internal static string TradeOpened {
            get {
                return ResourceManager.GetString("TradeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Status:.
        /// </summary>
        internal static string TradeStatus {
            get {
                return ResourceManager.GetString("TradeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA code mismatch. Retry in 15 seconds..
        /// </summary>
        internal static string TwoFACodeMismatchRetryIn15Seconds {
            get {
                return ResourceManager.GetString("TwoFACodeMismatchRetryIn15Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Authenticated!.
        /// </summary>
        internal static string UserAuthenticated {
            get {
                return ResourceManager.GetString("UserAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebAPIUserNonce Error:.
        /// </summary>
        internal static string WebAPIUserNonceError {
            get {
                return ResourceManager.GetString("WebAPIUserNonceError", resourceCulture);
            }
        }
    }
}
